# -----------------------------------------------------------------------------
# openapi/paths/drivers/trips/drivers.trips.openapi.yaml
# -----------------------------------------------------------------------------

# GET /api/v1/drivers/{driverId}/trips
get:
  tags:
    - Driver Trips
  operationId:  getDriverTrips
  summary:      Get List of Driver Trips
  description:  >
    Retrieve a list of trips for a driver.
  parameters:
    - $ref: '../../../components/parameters/driver-id.param.yaml'
    - $ref: '../../../components/parameters/page.param.yaml'
    - $ref: '../../../components/parameters/page-size.param.yaml'
    - $ref: '../../../components/parameters/sort-by.param.yaml'
    - $ref: '../../../components/headers/date.header.yaml'
  responses:
    '200':
      description:  'OK'
      content:
        application/json:
          schema:
            properties:
              trips: 
                $ref: '../../../components/schemas/trip/trip-collection.schema.yaml'
              metadata:
                $ref: '../../../components/schemas/lib/pagination.schema.yaml'
    '400':
      $ref: '../../../components/responses/400.bad-request.response.yaml'
    '404':
      $ref: '../../../components/responses/404.not-found.response.yaml'


